<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlayersSeeder extends Seeder
{
    public function run()
    {
        $playersData  = [
            [
                'current_team_id' => 1,
                'first_name' => 'wael',
                'middle_name' => 'adnan',
                'last_name' => 'awada',
                'birthdate' => '2024-03-09',
                'email' => 'wael.awada@outlook.com',
                'phone_number' => '78860108',
                'national_id_upload' => 'public/national_ids/Z3aE0OcutWXtNF6ZbCARYOl75SPOXB27Lsf4Z8QU.jpg',
                'country_id' => 3,
                'nickname' => 'sharky do do do',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 2,
                'first_name' => 'Luka',
                'middle_name' => 'Aleksandr',
                'last_name' => 'Petrov',
                'birthdate' => '2023-05-15',
                'email' => 'luka.petrov@example.com',
                'phone_number' => '5551234567',
                'national_id_upload' => 'public/national_ids/Luka_Petrov_ID.jpg',
                'country_id' => 5,
                'nickname' => 'Thunderfoot',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 3,
                'first_name' => 'Elena',
                'middle_name' => 'Marie',
                'last_name' => 'Garcia',
                'birthdate' => '2023-08-22',
                'email' => 'elena.garcia@example.com',
                'phone_number' => '5559876543',
                'national_id_upload' => 'public/national_ids/Elena_Garcia_ID.jpg',
                'country_id' => 7,
                'nickname' => 'Dynamo',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 4,
                'first_name' => 'Kenta',
                'middle_name' => 'Takumi',
                'last_name' => 'Sato',
                'birthdate' => '2023-01-10',
                'email' => 'kenta.sato@example.com',
                'phone_number' => '5555678901',
                'national_id_upload' => 'public/national_ids/Kenta_Sato_ID.jpg',
                'country_id' => 9,
                'nickname' => 'Blitz',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 5,
                'first_name' => 'Aisha',
                'middle_name' => 'Fatima',
                'last_name' => 'Khan',
                'birthdate' => '2023-11-03',
                'email' => 'aisha.khan@example.com',
                'phone_number' => '5552345678',
                'national_id_upload' => 'public/national_ids/Aisha_Khan_ID.jpg',
                'country_id' => 11,
                'nickname' => 'Phoenix',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 6,
                'first_name' => 'Diego',
                'middle_name' => 'Javier',
                'last_name' => 'Hernandez',
                'birthdate' => '2023-06-18',
                'email' => 'diego.hernandez@example.com',
                'phone_number' => '5558765432',
                'national_id_upload' => 'public/national_ids/Diego_Hernandez_ID.jpg',
                'country_id' => 13,
                'nickname' => 'Raptor',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 7,
                'first_name' => 'Hikari',
                'middle_name' => 'Yuki',
                'last_name' => 'Tanaka',
                'birthdate' => '2023-09-25',
                'email' => 'hikari.tanaka@example.com',
                'phone_number' => '5553456789',
                'national_id_upload' => 'public/national_ids/Hikari_Tanaka_ID.jpg',
                'country_id' => 15,
                'nickname' => 'Blaze',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 8,
                'first_name' => 'Aiden',
                'middle_name' => 'Michael',
                'last_name' => 'Smith',
                'birthdate' => '2023-03-12',
                'email' => 'aiden.smith@example.com',
                'phone_number' => '5557654321',
                'national_id_upload' => 'public/national_ids/Aiden_Smith_ID.jpg',
                'country_id' => 17,
                'nickname' => 'Striker',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 9,
                'first_name' => 'Sophie',
                'middle_name' => 'Elizabeth',
                'last_name' => 'Wilson',
                'birthdate' => '2023-07-28',
                'email' => 'sophie.wilson@example.com',
                'phone_number' => '5552345678',
                'national_id_upload' => 'public/national_ids/Sophie_Wilson_ID.jpg',
                'country_id' => 19,
                'nickname' => 'Tornado',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 10,
                'first_name' => 'Mohammed',
                'middle_name' => 'Ali',
                'last_name' => 'Ahmed',
                'birthdate' => '2023-04-05',
                'email' => 'mohammed.ahmed@example.com',
                'phone_number' => '5558765432',
                'national_id_upload' => 'public/national_ids/Mohammed_Ahmed_ID.jpg',
                'country_id' => 21,
                'nickname' => 'Whirlwind',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 1,
                'first_name' => 'Emma',
                'middle_name' => 'Grace',
                'last_name' => 'Jones',
                'birthdate' => '2023-12-10',
                'email' => 'emma.jones@example.com',
                'phone_number' => '5559876543',
                'national_id_upload' => 'public/national_ids/Emma_Jones_ID.jpg',
                'country_id' => 23,
                'nickname' => 'Cyclone',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 2,
                'first_name' => 'Ryota',
                'middle_name' => 'Kenji',
                'last_name' => 'Yamamoto',
                'birthdate' => '2023-02-14',
                'email' => 'ryota.yamamoto@example.com',
                'phone_number' => '5558765432',
                'national_id_upload' => 'public/national_ids/Ryota_Yamamoto_ID.jpg',
                'country_id' => 25,
                'nickname' => 'Typhoon',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 3,
                'first_name' => 'Isabella',
                'middle_name' => 'Sophia',
                'last_name' => 'Brown',
                'birthdate' => '2023-09-07',
                'email' => 'isabella.brown@example.com',
                'phone_number' => '5552345678',
                'national_id_upload' => 'public/national_ids/Isabella_Brown_ID.jpg',
                'country_id' => 27,
                'nickname' => 'Storm',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 4,
                'first_name' => 'Kenji',
                'middle_name' => 'Haruto',
                'last_name' => 'Suzuki',
                'birthdate' => '2023-06-21',
                'email' => 'kenji.suzuki@example.com',
                'phone_number' => '5553456789',
                'national_id_upload' => 'public/national_ids/Kenji_Suzuki_ID.jpg',
                'country_id' => 29,
                'nickname' => 'Thunder',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 5,
                'first_name' => 'Sofia',
                'middle_name' => 'Valentina',
                'last_name' => 'Martinez',
                'birthdate' => '2023-11-14',
                'email' => 'sofia.martinez@example.com',
                'phone_number' => '5559876543',
                'national_id_upload' => 'public/national_ids/Sofia_Martinez_ID.jpg',
                'country_id' => 31,
                'nickname' => 'Hurricane',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 6,
                'first_name' => 'Ryo',
                'middle_name' => 'Naoki',
                'last_name' => 'Tanaka',
                'birthdate' => '2023-04-17',
                'email' => 'ryo.tanaka@example.com',
                'phone_number' => '5551234567',
                'national_id_upload' => 'public/national_ids/Ryo_Tanaka_ID.jpg',
                'country_id' => 33,
                'nickname' => 'Tempest',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 7,
                'first_name' => 'Aya',
                'middle_name' => 'Yui',
                'last_name' => 'Nakamura',
                'birthdate' => '2023-10-30',
                'email' => 'aya.nakamura@example.com',
                'phone_number' => '5558765432',
                'national_id_upload' => 'public/national_ids/Aya_Nakamura_ID.jpg',
                'country_id' => 35,
                'nickname' => 'Gale',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 8,
                'first_name' => 'Liam',
                'middle_name' => 'Jacob',
                'last_name' => 'Taylor',
                'birthdate' => '2023-05-24',
                'email' => 'liam.taylor@example.com',
                'phone_number' => '5552345678',
                'national_id_upload' => 'public/national_ids/Liam_Taylor_ID.jpg',
                'country_id' => 37,
                'nickname' => 'Whirlpool',
                'playing_side' => 'left',
            ],
            [
                'current_team_id' => 9,
                'first_name' => 'Leila',
                'middle_name' => 'Fatima',
                'last_name' => 'Abdullah',
                'birthdate' => '2024-02-18',
                'email' => 'leila.abdullah@example.com',
                'phone_number' => '5559876543',
                'national_id_upload' => 'public/national_ids/Leila_Abdullah_ID.jpg',
                'country_id' => 39,
                'nickname' => 'Tsunami',
                'playing_side' => 'right',
            ],
            [
                'current_team_id' => 10,
                'first_name' => 'Max',
                'middle_name' => 'Alexander',
                'last_name' => 'Johnson',
                'birthdate' => '2024-06-11',
                'email' => 'max.johnson@example.com',
                'phone_number' => '5551234567',
                'national_id_upload' => 'public/national_ids/Max_Johnson_ID.jpg',
                'country_id' => 41,
                'nickname' => 'Cyclone',
                'playing_side' => 'left',
            ],
            
            
            
        ];

        foreach ($playersData  as $playerData ) {
            $playerData['created_at'] = now();
            $playerData['updated_at'] = now();
            DB::table('players')->insertGetId($playerData);
        }


    }
}


